export const KAPITEL = [
  '1 Einleitung',
  '1.1 Ausgangslage',
  '1.2 Zielsetzung und Forschungsfrage',
  '1.3 Vorgehen',
  '1.4 Abgrenzungen und allgemeine Begriffsdefinitionen',
  '2 Theoretischer Teil',
  '2.1 Gold als Anlageklasse',
  '2.1.1 Eigenschaften und Besonderheiten von Gold als Anlage',
  '2.1.2 Historische Entwicklung: vom Goldstandard zur heutigen Bedeutung',
  '2.1.3 Gold im Vergleich zu anderen Anlageoptionen',
  '2.2 Funktionen von Gold im Finanzsystem',
  '2.2.1 Gold als Schutz vor Inflation und Kaufkraftverlust',
  '2.2.2 Gold als Absicherung in wirtschaftlichen und politischen Krisen',
  '2.2.3 Gold zur Risikostreuung im Anlageportfolio',
  '2.3 Die US-Notenbank — Aufgaben und geldpolitische Instrumente',
  '2.3.1 Aufgaben und Ziele der Federal Reserve',
  '2.3.2 Die Zinspolitik als wichtigstes Steuerungsmittel',
  '2.3.3 Einfluss von Zinsankündigungen auf die Finanzmärkte',
  '2.4 Zusammenhang zwischen Zinsen und dem Goldpreis',
  '2.4.1 Warum hohe Zinsen den Goldpreis eigentlich senken sollten',
  '2.4.2 Wie Inflation und Kaufkraftverlust Gold trotzdem attraktiv machen',
  '2.4.3 Wie das Vertrauen in den US-Dollar das Anlegerverhalten beeinflusst',
  '2.5 Weitere Einflussfaktoren auf den Goldpreis',
  '2.5.1 Geopolitische Spannungen, Kriege und Handelskonflikte',
  '2.5.2 Goldkäufe durch Zentralbanken und deren Bedeutung',
  '2.5.3 Spekulation und Marktpsychologie als kurzfristige Treiber',
  '2.6 Gold im aktuellen Hochzinsumfeld',
  '2.6.1 Theoretischer Erwartungswert vs. tatsächliche Preisentwicklung',
  '2.6.2 Erklärungsansätze für den Anstieg trotz hoher Zinsen',
  '2.6.3 Vergleich mit früheren Hochzinsphasen: die 1980er Jahre',
  '3 Methodische Vorgehensweise',
  '3.1 Untersuchungsziel / Forschungsfrage',
  '3.2 Erhebungsmethode und Instrument',
  '3.3 Wahl der Praxisfälle / Experten / Stichprobe',
  '3.4 Ablauf / Datenaufbereitung',
  '4 Praktischer Teil',
  '4.1 Ergebnisse 1',
  '4.2 Ergebnisse 2',
  '4.3 Methodische Kritik',
  '5 Schlussfolgerungen und Ausblick',
  '5.1 Schlussfolgerungen / Implikationen',
  '5.2 Kritische Würdigung',
  '5.3 Ausblick',
  '6 Literaturverzeichnis',
  '7 Anhang',
  '8 Ehrenwörtliche Erklärung',
]
